-- PromptGallery starter prompts (52)
insert into public.prompts (
  id,
  title,
  description,
  prompt_text,
  category,
  example_image_url,
  tags,
  is_featured,
  use_count
)
values
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c101',
  'Studio Ghibli Anime',
  'Miyazaki-inspired watercolor anime portrait with warm cinematic mood.',
  $$studio ghibli anime style portrait, hand-painted watercolor texture, soft sunlit haze, expressive eyes, clean face anatomy, pastel natural palette, painterly foliage background, gentle film grain, preserve source face identity and pose, high detail illustration, no text, no watermark$$,
  'Anime',
  'https://images.unsplash.com/photo-1519699047748-de8e457a634e?auto=format&fit=crop&w=1200&q=80',
  array['anime', 'ghibli', 'portrait', 'watercolor'],
  true,
  248
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c102',
  'Pixar 3D Character',
  'Bright family-film 3D look with expressive eyes and polished render.',
  $$pixar style 3d character render, expressive face, stylized proportions, soft global illumination, smooth skin shading, cinematic color separation, playful storybook background, keep original expression and silhouette, high-end animation render quality, no text$$,
  'Cartoon',
  'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=1200&q=80',
  array['pixar', '3d', 'character', 'animation'],
  true,
  226
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c103',
  'Oil Painting Master',
  'Classical museum-style oil painting with dramatic brushwork.',
  $$renaissance oil painting on linen, rich impasto brush strokes, old master lighting, warm skin tones, dramatic chiaroscuro, museum grade composition, preserve subject likeness, ornate painterly background, high detail texture, no modern artifacts$$,
  'Portrait',
  'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=1200&q=80',
  array['oil painting', 'renaissance', 'art', 'portrait'],
  false,
  189
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c104',
  'Pencil Sketch Artist',
  'Detailed graphite drawing with realistic cross-hatching.',
  $$graphite pencil sketch portrait, refined crosshatching, soft shading gradients, paper texture grain, realistic line control, monochrome tonal depth, preserve face geometry and expression, studio artist drawing style, crisp contours, no color$$,
  'Art',
  'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?auto=format&fit=crop&w=1200&q=80',
  array['sketch', 'graphite', 'drawing', 'monochrome'],
  false,
  142
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c105',
  'Watercolor Dream',
  'Soft pastel watercolor finish with dreamy brush diffusion.',
  $$delicate watercolor illustration, pastel harmony, wet-on-wet brush edges, textured handmade paper, airy highlights, soft bloom lighting, preserve subject identity and framing, artistic hand-painted finish, elegant minimal outlines$$,
  'Art',
  'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&w=1200&q=80',
  array['watercolor', 'pastel', 'art', 'dreamy'],
  false,
  157
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c106',
  'Comic Book Hero',
  'Bold comic ink lines and action-heavy color treatment.',
  $$comic book hero illustration, bold black inks, halftone shadow pattern, dramatic key light, high saturation primary colors, dynamic action framing, preserve face and pose, graphic novel polish, sharp edge detailing, no speech bubbles$$,
  'Cartoon',
  'https://images.unsplash.com/photo-1527980965255-d3b416303d12?auto=format&fit=crop&w=1200&q=80',
  array['comic', 'hero', 'marvel style', 'illustration'],
  false,
  163
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c107',
  'Vogue Magazine Cover',
  'High-fashion editorial lighting and premium skin finish.',
  $$vogue editorial portrait, luxury fashion cover mood, controlled studio light, premium skin retouch look, couture styling, confident pose, preserve identity and proportions, clean background gradient, ultra sharp detail, no readable text$$,
  'Portrait',
  'https://images.unsplash.com/photo-1552374196-c4e7ffc6e126?auto=format&fit=crop&w=1200&q=80',
  array['fashion', 'vogue', 'editorial', 'portrait'],
  true,
  178
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c108',
  'Cinematic Portrait',
  'Movie still grade with dramatic contrast and shallow depth.',
  $$cinematic portrait grade, anamorphic flare, teal and amber color separation, dramatic contrast, realistic skin detail, depth-of-field bokeh, preserve original identity, premium film post-processing, no text or logo$$,
  'Portrait',
  'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=1200&q=80',
  array['cinematic', 'movie still', 'portrait', 'grading'],
  true,
  211
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c109',
  'Renaissance Painting',
  'Rembrandt-like classical portrait with rich chiaroscuro.',
  $$rembrandt inspired portrait painting, candlelit chiaroscuro, sfumato blending, classical costume details, old world canvas texture, realistic eyes, preserve identity and posture, museum quality painterly realism, no modern props$$,
  'Portrait',
  'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=1200&q=80',
  array['renaissance', 'rembrandt', 'classical', 'portrait'],
  false,
  132
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c110',
  'Sticker Art Cute',
  'Kawaii sticker look with clean flat outlines and glossy finish.',
  $$cute kawaii sticker art, clean vector-like line art, pastel palette, glossy sticker texture, simplified facial geometry, playful expression, preserve recognizable features, transparent background feel, crisp printable look$$,
  'Cartoon',
  'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1200&q=80',
  array['sticker', 'kawaii', 'cute', 'illustration'],
  false,
  149
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c111',
  'Cyberpunk City',
  'Neon cyberpunk dystopia with rain reflections and fog.',
  $$cyberpunk city atmosphere, neon pink and cyan signs, rainy pavement reflections, volumetric fog, holographic ad boards, gritty urban textures, preserve perspective and subject, high-contrast night cinematography, no text overlays$$,
  'Cyberpunk',
  'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=1200&q=80',
  array['cyberpunk', 'neon', 'city', 'future'],
  true,
  237
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c112',
  'Dark Fantasy Warrior',
  'Epic game-art warrior portrait in dark fantasy world.',
  $$dark fantasy warrior concept art, heavy armor detailing, moonlit rim light, atmospheric smoke, mystical runes, dramatic cinematic framing, preserve face identity, hyper-detailed textures, epic game artwork finish$$,
  'Fantasy',
  'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
  array['dark fantasy', 'warrior', 'game art', 'epic'],
  false,
  171
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c113',
  'Space Explorer',
  'Astronaut style transformation with deep nebula backdrop.',
  $$space explorer portrait, astronaut suit detailing, cosmic nebula background, cinematic starlight highlights, realistic metallic reflections, preserve facial identity in helmet view, ultra-detailed sci-fi render, high dynamic range$$,
  'Fantasy',
  'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?auto=format&fit=crop&w=1200&q=80',
  array['space', 'astronaut', 'sci-fi', 'nebula'],
  false,
  118
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c114',
  'Dragon Tamer',
  'Fantasy dragon rider concept with cinematic fire atmosphere.',
  $$dragon rider fantasy illustration, epic scale composition, glowing embers, dramatic sky, ornate armor and cloth, preserve subject posture and likeness, cinematic fantasy concept art, detailed creature anatomy, no text$$,
  'Fantasy',
  'https://images.unsplash.com/photo-1511884642898-4c92249e20b6?auto=format&fit=crop&w=1200&q=80',
  array['dragon', 'fantasy', 'epic', 'concept art'],
  false,
  103
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c115',
  'Steampunk Victorian',
  'Brass-and-gears steampunk portrait with Victorian styling.',
  $$steampunk victorian portrait, brass gears and pipes, leather and copper costume, warm tungsten lighting, smoky atmosphere, preserve identity and pose, retro-futurist design language, high-detail textures$$,
  'Fantasy',
  'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1200&q=80',
  array['steampunk', 'victorian', 'retro future', 'portrait'],
  false,
  94
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c116',
  'Underwater World',
  'Bioluminescent deep-sea fantasy with floating particles.',
  $$underwater fantasy world, bioluminescent glow, floating particles, blue-green caustic light, dreamy aquatic ambience, preserve subject silhouette and expression, detailed water refraction, cinematic ocean depth$$,
  'Nature',
  'https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?auto=format&fit=crop&w=1200&q=80',
  array['underwater', 'ocean', 'bioluminescent', 'fantasy'],
  false,
  112
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c117',
  'Vintage 1970s Film',
  'Grainy analog film texture with warm nostalgic color shifts.',
  $$1970s analog film aesthetic, warm faded tones, fine grain, subtle halation, soft contrast, candid cinematic framing, preserve identity and composition, realistic vintage print look$$,
  'Vintage',
  'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1200&q=80',
  array['vintage', 'film', 'retro', 'grain'],
  true,
  204
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c118',
  'Retro Pixel Art',
  '16-bit arcade pixel style with dithering and chunky sprites.',
  $$retro 16-bit pixel art conversion, limited palette, crisp pixel edge, sprite shading, balanced dithering, nostalgic arcade vibe, preserve key facial landmarks, no blur, no text$$,
  'Cartoon',
  'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=1200&q=80',
  array['pixel art', 'retro', '16-bit', 'arcade'],
  false,
  188
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c119',
  'Vaporwave Aesthetic',
  'Pastel retro-wave styling with glossy neon gradients.',
  $$vaporwave portrait style, pastel magenta and cyan gradient, retro sunset glow, synthetic chrome accents, surreal geometry, preserve person and camera angle, dreamy 80s digital art atmosphere$$,
  'Vintage',
  'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
  array['vaporwave', 'pastel', 'retro', 'neon'],
  false,
  145
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c120',
  'Black and White Film Noir',
  '1940s noir look with moody shadows and silver grain.',
  $$black and white film noir portrait, hard key lighting, deep shadows, silver halide grain, moody detective era tone, preserve identity, dramatic monochrome contrast, classic cinema composition$$,
  'Vintage',
  'https://images.unsplash.com/photo-1461280360983-bd93eaa5051b?auto=format&fit=crop&w=1200&q=80',
  array['film noir', 'black and white', 'cinematic', 'vintage'],
  false,
  96
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c121',
  '90s Cartoon Network',
  'Flat 90s toon colors with playful exaggerated expressions.',
  $$1990s cartoon network style, flat cel-shaded colors, bold outlines, quirky character expression, nostalgic TV animation look, preserve identity cues, clean simplified forms, no text$$,
  'Cartoon',
  'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=1200&q=80',
  array['90s', 'cartoon', 'nostalgia', 'toon'],
  false,
  124
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c122',
  'Bollywood Poster',
  'Colorful Hindi film poster style with dramatic lights and typography space.',
  $$bollywood movie poster aesthetic, vibrant cinematic colors, dramatic hero lighting, dust and flare particles, stylized poster framing, preserve identity and pose, high contrast masala film mood, no actual text$$,
  'India Special',
  'https://images.unsplash.com/photo-1524492449090-1d291f7f89e3?auto=format&fit=crop&w=1200&q=80',
  array['bollywood', 'india', 'poster', 'cinematic'],
  true,
  301
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c123',
  'Madhubani Art',
  'Traditional Mithila folk patterns with hand-drawn symmetry.',
  $$madhubani folk art style portrait, intricate linework, symbolic motifs, flat vivid colors, hand-drawn border details, preserve subject silhouette, traditional mithila aesthetic, paper texture finish$$,
  'India Special',
  'https://images.unsplash.com/photo-1577083552431-6e5fd01988f9?auto=format&fit=crop&w=1200&q=80',
  array['madhubani', 'mithila', 'folk art', 'india'],
  true,
  255
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c124',
  'Warli Tribal Art',
  'Minimal tribal storytelling style in monochrome earth tones.',
  $$warli tribal art style, stick-figure geometry, earthy monochrome palette, handcrafted mural texture, folk storytelling motifs, preserve key subject posture, authentic tribal composition$$,
  'India Special',
  'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=1200&q=80',
  array['warli', 'tribal', 'folk', 'india'],
  true,
  212
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c125',
  'Rajasthani Miniature',
  'Royal miniature painting with ornate details and jewel tones.',
  $$rajasthani miniature painting style, intricate ornamental patterns, royal attire details, jewel-tone palette, flat perspective composition, preserve face identity, heritage manuscript texture, elegant traditional finish$$,
  'India Special',
  'https://images.unsplash.com/photo-1604076913837-52ab5629fba9?auto=format&fit=crop&w=1200&q=80',
  array['rajasthani', 'miniature', 'heritage', 'india'],
  true,
  198
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c126',
  'Diwali Glow',
  'Golden festive ambience with diyas, rangoli and soft sparkle.',
  $$diwali festival portrait style, golden diya lighting, rangoli accents, festive bokeh sparkles, rich celebratory colors, preserve identity and expression, elegant festive attire vibe, cinematic warmth$$,
  'India Special',
  'https://images.unsplash.com/photo-1605379399642-870262d3d051?auto=format&fit=crop&w=1200&q=80',
  array['diwali', 'festival', 'india', 'golden'],
  true,
  287
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c127',
  'Holi Colors',
  'Burst of Holi gulal powders with high-energy celebration look.',
  $$holi festival color explosion, vibrant gulal powders in motion, joyful festival lighting, dynamic action framing, preserve face and pose, high saturation celebratory tone, cinematic freeze-frame look$$,
  'India Special',
  'https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=1200&q=80',
  array['holi', 'colors', 'festival', 'india'],
  true,
  294
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c128',
  'Navratri Garba',
  'Vibrant garba-night styling with mirror-work and festive energy.',
  $$navratri garba celebration style, vibrant lehenga textures, mirror-work embroidery highlights, festive night lights, energetic dance composition, preserve subject identity and motion, rich gujarati cultural palette$$,
  'India Special',
  'https://images.unsplash.com/photo-1535324492437-d8dea70a38a7?auto=format&fit=crop&w=1200&q=80',
  array['navratri', 'garba', 'festival', 'india'],
  true,
  176
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c129',
  'South Indian Temple Art',
  'Tanjore-inspired gold-leaf devotional art treatment.',
  $$south indian tanjore art style, gold foil detailing, temple mural texture, devotional portrait framing, rich red and green accents, preserve identity and posture, ornate sacred art aesthetic$$,
  'India Special',
  'https://images.unsplash.com/photo-1603912699214-92627f304eb6?auto=format&fit=crop&w=1200&q=80',
  array['tanjore', 'temple art', 'south india', 'heritage'],
  true,
  167
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c130',
  'Punjabi Wedding',
  'Rich bridal palette with embroidery and festive wedding glamour.',
  $$punjabi wedding portrait aesthetic, rich jewel tones, embroidered fabric detail, festive bokeh lights, glamorous bridal styling, preserve face identity, cinematic celebratory mood, high detail textiles$$,
  'India Special',
  'https://images.unsplash.com/photo-1606800052052-a08af7148866?auto=format&fit=crop&w=1200&q=80',
  array['punjabi', 'wedding', 'bridal', 'india'],
  true,
  214
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c131',
  'Eid Mubarak Style',
  'Elegant geometric motifs and moonlit festive sophistication.',
  $$eid mubarak festive portrait style, elegant islamic geometric patterns, crescent moon ambience, emerald and gold palette, soft lantern glow, preserve identity and expression, refined celebratory composition$$,
  'India Special',
  'https://images.unsplash.com/photo-1519817650390-64a93db511aa?auto=format&fit=crop&w=1200&q=80',
  array['eid', 'festival', 'islamic art', 'india'],
  true,
  182
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c132',
  'Low Poly Geometric',
  'Triangulated low-poly art with modern digital sculpture feel.',
  $$low poly geometric portrait, triangulated facets, crisp polygon edges, soft ambient occlusion, modern digital sculpture style, preserve overall silhouette and expression, clean color blocking$$,
  'Art',
  'https://images.unsplash.com/photo-1460574283810-2aab119d8511?auto=format&fit=crop&w=1200&q=80',
  array['low poly', 'geometric', '3d', 'stylized'],
  false,
  121
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c133',
  'Neon Glow Portrait',
  'Electric light painting portrait with futuristic neon contours.',
  $$neon glow portrait style, electric rim lights, cyan magenta gradients, glossy skin highlights, atmospheric haze, preserve identity and camera angle, nightclub cinematic mood, high contrast details$$,
  'Portrait',
  'https://images.unsplash.com/photo-1516726817505-f5ed825624d8?auto=format&fit=crop&w=1200&q=80',
  array['neon', 'glow', 'portrait', 'trending'],
  false,
  169
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c134',
  'Impressionist Painting',
  'Monet-like brushstroke interpretation with luminous daylight.',
  $$impressionist painting portrait, monet-inspired brushwork, broken color strokes, luminous daylight palette, soft depth atmosphere, preserve composition and face identity, museum-grade painterly finish$$,
  'Art',
  'https://images.unsplash.com/photo-1511884642898-4c92249e20b6?auto=format&fit=crop&w=1200&q=80',
  array['impressionist', 'monet', 'painting', 'art'],
  false,
  117
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c135',
  'Surreal Dream',
  'Dali-inspired surreal composition with dreamlike symbolism.',
  $$surreal dreamscape portrait, dali-inspired distortions, symbolic floating objects, dramatic sky gradients, cinematic depth, preserve recognizable face cues, imaginative fine-art atmosphere, high detail surreal painting$$,
  'Fantasy',
  'https://images.unsplash.com/photo-1473177104440-ffee2f376098?auto=format&fit=crop&w=1200&q=80',
  array['surreal', 'dream', 'dali', 'art'],
  false,
  108
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c136',
  'Studio Photography',
  'Clean high-detail studio look with white seamless backdrop.',
  $$professional studio portrait photography, seamless white background, softbox lighting setup, crisp focus, color accuracy, subtle shadows, preserve identity and realistic texture, catalogue-grade output$$,
  'Portrait',
  'https://images.unsplash.com/photo-1585386959984-a4155224a1ad?auto=format&fit=crop&w=1200&q=80',
  array['studio', 'clean', 'photography', 'pro'],
  false,
  141
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c137',
  'Golden Hour Portrait',
  'Warm sunset color grade with flattering skin highlights.',
  $$golden hour portrait grade, warm sunlit rim light, soft lens flare, natural skin glow, shallow depth of field, preserve identity and framing, cinematic sunset aesthetic, high detail photo realism$$,
  'Portrait',
  'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
  array['golden hour', 'sunset', 'portrait', 'warm'],
  false,
  174
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c138',
  'Anime Chibi',
  'Super-cute chibi anime transformation with oversized features.',
  $$anime chibi character style, oversized cute eyes, tiny body proportions, soft pastel shading, playful expression, preserve key facial identity cues, clean cel-shaded lines, adorable sticker-ready output$$,
  'Anime',
  'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1200&q=80',
  array['anime', 'chibi', 'cute', 'kawaii'],
  false,
  156
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c139',
  'Tattoo Sketch',
  'Bold black ink tattoo flash look with high contrast contours.',
  $$tattoo flash sketch style, bold black linework, high contrast shading, hand-drawn ink texture, old-school tattoo stencil vibe, preserve main subject silhouette, graphic monochrome finish$$,
  'Art',
  'https://images.unsplash.com/photo-1517423440428-a5a00ad493e8?auto=format&fit=crop&w=1200&q=80',
  array['tattoo', 'ink', 'sketch', 'flash'],
  false,
  111
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c140',
  'Mosaic Art',
  'Byzantine-inspired colorful tile mosaic transformation.',
  $$byzantine mosaic portrait style, colorful ceramic tiles, intricate tessellation patterns, reflective grout highlights, preserve facial proportions and composition, handcrafted artisan look, rich decorative finish$$,
  'Art',
  'https://images.unsplash.com/photo-1518991791750-749c372f7d43?auto=format&fit=crop&w=1200&q=80',
  array['mosaic', 'tile art', 'byzantine', 'decorative'],
  false,
  98
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c141',
  'Action Figure Blister Pack',
  'Turn portraits into collectible toy packaging style cards.',
  $$collectible action figure blister pack concept, transparent toy box shell, branded hobby-store shelf look, studio product lighting, highly detailed miniature likeness, preserve face identity and outfit colors, polished plastic reflections, premium packaging design aesthetic, no readable logo text$$,
  'Cartoon',
  'https://images.unsplash.com/photo-1514066558159-fc8c737ef259?auto=format&fit=crop&w=1200&q=80',
  array['action figure', 'toy box', 'collector', '2025 trend'],
  true,
  412
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c142',
  'Barbie Box Portrait',
  'Famous doll-box aesthetic with polished pink studio styling.',
  $$doll box portrait style, polished toy packaging layout, glossy pink and pastel palette, high-key studio lighting, clean retail shelf composition, preserve facial likeness and pose, smooth plastic-inspired finish, beauty campaign quality, no readable text$$,
  'Cartoon',
  'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1200&q=80',
  array['barbie style', 'doll box', 'pink aesthetic', 'viral'],
  true,
  365
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c143',
  'Mini Figurine Diorama',
  'Nano-figure trend with handcrafted diorama environment.',
  $$miniature figurine portrait in handcrafted diorama scene, tiny scale realism, macro lens depth, textured model environment, warm softbox lighting, preserve recognizable face traits, stylized toy-grade sculpt details, high-detail collectible render, no logo text$$,
  'Art',
  'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1200&q=80',
  array['miniature', 'diorama', 'figurine', 'nano trend'],
  true,
  338
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c144',
  'LinkedIn Pro Headshot',
  'Trending professional profile-photo enhancement look.',
  $$professional linkedin headshot style, clean neutral background, flattering key and fill lighting, realistic skin texture, natural confidence expression, tailored wardrobe refinement, preserve exact face identity, premium corporate portrait polish, no over-smoothing, no text$$,
  'Portrait',
  'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=1200&q=80',
  array['linkedin', 'headshot', 'professional', 'career'],
  true,
  327
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c145',
  'Passport to Studio Portrait',
  'Viral before-after style from plain passport to premium studio shot.',
  $$passport photo to studio portrait transformation, natural skin detail, clean backdrop gradient, soft cinematic lighting, realistic hair cleanup, preserve exact identity and proportions, premium DSLR look, subtle color grading, no watermark or text$$,
  'Portrait',
  'https://images.unsplash.com/photo-1544723795-3fb6469f5b39?auto=format&fit=crop&w=1200&q=80',
  array['passport glow-up', 'studio', 'portrait', 'before after'],
  true,
  295
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c146',
  '90s Yearbook Throwback',
  'Retro school-photo trend with classic film grain and backdrop.',
  $$1990s yearbook portrait style, retro school backdrop, flash-lit studio look, soft grain texture, nostalgic color cast, preserve face identity and expression, subtle analog imperfections, authentic yearbook composition, no text$$,
  'Vintage',
  'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1200&q=80',
  array['90s', 'yearbook', 'retro', 'nostalgia'],
  true,
  281
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c147',
  'LEGO Minifigure Avatar',
  'Blocky toy-avatar aesthetic inspired by minifigure design.',
  $$lego-style minifigure portrait transformation, blocky toy proportions, plastic material shading, playful construction-set palette, studio toy-photography lighting, preserve key identity markers, crisp clean edges, collectible figurine presentation, no text$$,
  'Cartoon',
  'https://images.unsplash.com/photo-1472457974886-0ebcd59440cc?auto=format&fit=crop&w=1200&q=80',
  array['lego style', 'minifigure', 'toy', 'avatar'],
  false,
  274
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c148',
  'Claymation Character',
  'Stop-motion clay character trend with handcrafted textures.',
  $$claymation portrait style, hand-sculpted clay texture, stop-motion film lighting, soft miniature set background, slightly imperfect artisanal details, preserve identity and expression, whimsical family-film mood, high-detail clay render, no text$$,
  'Cartoon',
  'https://images.unsplash.com/photo-1472396961693-142e6e269027?auto=format&fit=crop&w=1200&q=80',
  array['claymation', 'stop motion', 'character', 'viral style'],
  false,
  261
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c149',
  'Neon Drift Street Portrait',
  'Night city drift vibe with high-contrast neon mood.',
  $$night street neon drift aesthetic, electric cyan and magenta rim lights, wet asphalt reflections, motion energy blur accents, cinematic urban depth, preserve face identity and pose, high-contrast commercial color grade, no text overlay$$,
  'Cyberpunk',
  'https://images.unsplash.com/photo-1516726817505-f5ed825624d8?auto=format&fit=crop&w=1200&q=80',
  array['neon', 'street', 'cyberpunk', 'reel trend'],
  false,
  249
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c150',
  'Anime Sky Dreamscape',
  'Shinkai-like sky glow and atmospheric anime cinematic style.',
  $$cinematic anime portrait with luminous sky backdrop, dramatic cloud lighting, clean cel-shaded linework, dreamy color gradients, emotional storytelling mood, preserve exact face identity and pose, high-detail anime finish, no subtitle text$$,
  'Anime',
  'https://images.unsplash.com/photo-1516569422868-5c2f58f2f942?auto=format&fit=crop&w=1200&q=80',
  array['anime', 'sky', 'cinematic', 'dreamscape'],
  false,
  236
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c151',
  'RPG Character Card',
  'Gaming profile-card trend with fantasy class styling.',
  $$fantasy rpg character card portrait style, legendary class armor details, magical particle ambience, dramatic key light, cinematic game UI framing feel, preserve recognizable identity and facial geometry, ultra-detailed concept art polish, no readable text$$,
  'Fantasy',
  'https://images.unsplash.com/photo-1511884642898-4c92249e20b6?auto=format&fit=crop&w=1200&q=80',
  array['rpg', 'character card', 'fantasy', 'gaming'],
  false,
  223
),
(
  '7c9b0d3e-87ab-43f6-9fcb-1d3cf3e1c152',
  'Streetwear Lookbook Editorial',
  'Creator-friendly fashion lookbook style used in recent reels.',
  $$streetwear editorial portrait, urban fashion campaign lighting, premium texture retention on fabric, soft contrast background, dynamic model stance, preserve true face identity and body proportions, magazine-grade color grading, clean commercial finish, no text$$,
  'Portrait',
  'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1200&q=80',
  array['streetwear', 'editorial', 'lookbook', 'fashion'],
  false,
  214
)
on conflict (id) do update
set
  title = excluded.title,
  description = excluded.description,
  prompt_text = excluded.prompt_text,
  category = excluded.category,
  example_image_url = excluded.example_image_url,
  tags = excluded.tags,
  is_featured = excluded.is_featured,
  use_count = excluded.use_count;
